# Generated by Django 4.2.1 on 2023-05-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_code', models.CharField(max_length=10)),
                ('punch_time', models.DateTimeField()),
            ],
        ),
    ]
